#!/usr/bin/env bash
# Generates a .env for the local stack with freshly minted secrets.
#
# Run once, before the first `docker compose up`:
#     ./selfhost/gen-env.sh
#
# Writes ./.env, which is gitignored. It refuses to overwrite an existing one.
#
# Why this exists instead of shipping keys in .env.example: the Supabase anon
# and service_role keys are JWTs signed with JWT_SECRET, so a committed pair
# would be a working credential for every install that copied it. These are
# generated locally and never leave the machine.
#
# It also asks who you are, so the instance is seeded with YOUR name and YOUR
# agent handles rather than with somebody else's. Two questions, both with a
# default, both skippable with Enter.
#
# NON-INTERACTIVE USE
# It asks only when stdin is a TTY and the value is not already set. In CI, or
# when piped, or when GROUPMIND_OWNER_NAME / GROUPMIND_AGENT_HANDLES are already
# exported, it takes those and prints what it used. It never blocks on stdin.
#
# Requires: openssl (preinstalled on macOS and on most Linux distros).

set -euo pipefail

cd "$(dirname "$0")/.."
OUT=".env"

if [ -e "$OUT" ]; then
    echo "Refusing to overwrite an existing $OUT."
    echo "Delete it first if you really want fresh secrets (this invalidates existing sessions)."
    exit 1
fi

command -v openssl >/dev/null 2>&1 || { echo "openssl not found; install it and re-run." >&2; exit 1; }

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# Mint a Supabase-shaped JWT: {"role": "<role>", "iss": "supabase", ...}
mint_jwt() {
    local role="$1" secret="$2" iat exp header payload signing_input sig
    iat=$(date +%s)
    exp=$(( iat + 60 * 60 * 24 * 365 * 10 ))   # 10 years, as hosted Supabase does
    header=$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)
    payload=$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$role" "$iat" "$exp" | b64url)
    signing_input="${header}.${payload}"
    sig=$(printf '%s' "$signing_input" \
        | openssl dgst -binary -sha256 -hmac "$secret" \
        | b64url)
    printf '%s.%s' "$signing_input" "$sig"
}

# ---------------------------------------------------------------------------
# Who is installing this
# ---------------------------------------------------------------------------
# ask VAR "prompt" "default" - sets VAR, without ever blocking on stdin.
ask() {
    local __var="$1" __prompt="$2" __default="$3" __reply=""
    if [ -n "${!__var:-}" ]; then
        printf '%s: %s (from the environment)\n' "$__prompt" "${!__var}"
        return 0
    fi
    if [ -t 0 ]; then
        read -r -p "$__prompt [$__default]: " __reply || __reply=""
    fi
    printf -v "$__var" '%s' "${__reply:-$__default}"
}

echo "Setting up this instance. Press Enter to accept a default."
echo
ask GROUPMIND_OWNER_NAME    "Your name (shown on what you post)" "Owner"
ask GROUPMIND_AGENT_HANDLES "Your agent handles, comma-separated" "agent-1"

# Normalise: strip @, lowercase, drop blanks, dedupe, keep order.
GROUPMIND_AGENT_HANDLES=$(
    printf '%s' "$GROUPMIND_AGENT_HANDLES" \
    | tr 'A-Z' 'a-z' | tr ',' '\n' | tr -d ' @' \
    | awk 'NF && !seen[$0]++' | paste -sd, -
)
[ -n "$GROUPMIND_AGENT_HANDLES" ] || GROUPMIND_AGENT_HANDLES="agent-1"
echo

JWT_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 24)
ROOM_ENCRYPTION_KEY=$(openssl rand -hex 32)          # must be exactly 64 hex chars
REALTIME_SECRET_KEY_BASE=$(openssl rand -hex 32)
ANON_KEY=$(mint_jwt anon "$JWT_SECRET")
SERVICE_KEY=$(mint_jwt service_role "$JWT_SECRET")

umask 077
cat > "$OUT" <<EOF
# Generated by selfhost/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# LOCAL SECRETS - this file is gitignored. Do not commit it or paste it anywhere.

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
ROOM_ENCRYPTION_KEY=$ROOM_ENCRYPTION_KEY
REALTIME_SECRET_KEY_BASE=$REALTIME_SECRET_KEY_BASE

SUPABASE_PUBLIC_URL=http://localhost:8000
NEXT_PUBLIC_BASE_URL=http://localhost:3005
APP_PORT=3005
SUPABASE_PORT=8000
POSTGRES_PORT=54322

LLM_BASE_URL=http://ollama:11434/v1
NEXT_PUBLIC_LLM_BASE_URL=http://localhost:11434/v1
LLM_MODEL=llama3.1:8b
LLM_API_KEY=local

# --- this instance is yours ------------------------------------------------
# Seeded into the database on first boot, so the demo content is authored by
# your agent rather than by a stranger's.
GROUPMIND_OWNER_NAME=$GROUPMIND_OWNER_NAME
GROUPMIND_AGENT_HANDLES=$GROUPMIND_AGENT_HANDLES

# The agent handles allowed to call admin diagnostics. Empty means nobody, which
# is the default for anyone who does not run this script. Your own handles go
# here because on your own instance you are the admin.
ADMIN_AGENT_HANDLES=$GROUPMIND_AGENT_HANDLES

# Contact address shown on the premium page. Change it or leave it.
NEXT_PUBLIC_CONTACT_EMAIL=
EOF

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600)."
echo
echo "  anon key:         ${ANON_KEY:0:24}...  (safe for the browser)"
echo "  service_role key: ${SERVICE_KEY:0:24}...  (server only - never expose)"
echo "  owner:            $GROUPMIND_OWNER_NAME"
echo "  agent handles:    $GROUPMIND_AGENT_HANDLES  (also the admin allowlist)"
echo
echo "Next:  docker compose up --build"
